# PyTorch CUDA Test

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda")
x = torch.rand(10000, 10000, device=device)
y = x.to("cpu", torch.double)
print(x[0:5, 0:5])
print(y[0:5, 0:5])

tensor([[0.2076, 0.2335, 0.7513, 0.3559, 0.0743],
        [0.7606, 0.3788, 0.0648, 0.8628, 0.5447],
        [0.0100, 0.5309, 0.9162, 0.8445, 0.2397],
        [0.7017, 0.2206, 0.7480, 0.3963, 0.0934],
        [0.8556, 0.6081, 0.2961, 0.3992, 0.4661]], device='cuda:0')
tensor([[0.2076, 0.2335, 0.7513, 0.3559, 0.0743],
        [0.7606, 0.3788, 0.0648, 0.8628, 0.5447],
        [0.0100, 0.5309, 0.9162, 0.8445, 0.2397],
        [0.7017, 0.2206, 0.7480, 0.3963, 0.0934],
        [0.8556, 0.6081, 0.2961, 0.3992, 0.4661]], dtype=torch.float64)


In [4]:
%%time
for i in range(0,100):
    ym = y * .5
    
print(ym[0:5, 0:5])

tensor([[0.1038, 0.1168, 0.3756, 0.1780, 0.0371],
        [0.3803, 0.1894, 0.0324, 0.4314, 0.2724],
        [0.0050, 0.2654, 0.4581, 0.4222, 0.1198],
        [0.3508, 0.1103, 0.3740, 0.1982, 0.0467],
        [0.4278, 0.3040, 0.1480, 0.1996, 0.2330]], dtype=torch.float64)
CPU times: user 46.4 s, sys: 51.7 s, total: 1min 38s
Wall time: 12.5 s


In [5]:
%%time
for i in range(0,100):
    xm = x * .5

print(xm[0:5, 0:5])

tensor([[0.1038, 0.1168, 0.3756, 0.1780, 0.0371],
        [0.3803, 0.1894, 0.0324, 0.4314, 0.2724],
        [0.0050, 0.2654, 0.4581, 0.4222, 0.1198],
        [0.3508, 0.1103, 0.3740, 0.1982, 0.0467],
        [0.4278, 0.3040, 0.1480, 0.1996, 0.2330]], device='cuda:0')
CPU times: user 292 ms, sys: 131 ms, total: 424 ms
Wall time: 421 ms
