In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda")
x = torch.rand(10000, 10000, device=device)
y = x.to("cpu", torch.double)
print(x[0:5, 0:5])
print(y[0:5, 0:5])

tensor([[0.0169, 0.9467, 0.5363, 0.9584, 0.3156],
        [0.8019, 0.9053, 0.6847, 0.9064, 0.1007],
        [0.1737, 0.6080, 0.7540, 0.5925, 0.2054],
        [0.3939, 0.6765, 0.2907, 0.5377, 0.5120],
        [0.7550, 0.8331, 0.9017, 0.4315, 0.9879]], device='cuda:0')
tensor([[0.0169, 0.9467, 0.5363, 0.9584, 0.3156],
        [0.8019, 0.9053, 0.6847, 0.9064, 0.1007],
        [0.1737, 0.6080, 0.7540, 0.5925, 0.2054],
        [0.3939, 0.6765, 0.2907, 0.5377, 0.5120],
        [0.7550, 0.8331, 0.9017, 0.4315, 0.9879]], dtype=torch.float64)


In [4]:
%%time
for i in range(0,100):
    ym = y * .5
    
print(ym[0:5, 0:5])

tensor([[0.0085, 0.4733, 0.2681, 0.4792, 0.1578],
        [0.4010, 0.4527, 0.3423, 0.4532, 0.0504],
        [0.0869, 0.3040, 0.3770, 0.2963, 0.1027],
        [0.1969, 0.3383, 0.1453, 0.2688, 0.2560],
        [0.3775, 0.4166, 0.4508, 0.2158, 0.4940]], dtype=torch.float64)
CPU times: user 44.8 s, sys: 51.9 s, total: 1min 36s
Wall time: 12.3 s


In [5]:
%%time
for i in range(0,100):
    xm = (x * .5) /2

print(xm[0:5, 0:5])

tensor([[0.0042, 0.2367, 0.1341, 0.2396, 0.0789],
        [0.2005, 0.2263, 0.1712, 0.2266, 0.0252],
        [0.0434, 0.1520, 0.1885, 0.1481, 0.0513],
        [0.0985, 0.1691, 0.0727, 0.1344, 0.1280],
        [0.1887, 0.2083, 0.2254, 0.1079, 0.2470]], device='cuda:0')
CPU times: user 585 ms, sys: 240 ms, total: 826 ms
Wall time: 823 ms
